# Here are defined all the losses that can be used, with their parameters.
# You can also define combinations of losses, by specifying a list of losses and their corresponding weights.
# These combinations can then be referenced in the experiment configuration files.
losses:
  mse:
    calibration: 1
  mae:
    calibration: 1
  nllbg:
    calibration: 1
  f_mse:
    calibration: 1
    sigma: 2
  f_mae:
    calibration: 1
    sigma: 2
  wasserstein:
  gdl:
    calibration: 1
    p: 2
  gdl_l1:
    calibration: 1
    p: 1
  dssim:
    calibration: 1
  asym:
    calibration: 1
  spectral:
    p: 1
    calibration: 1
    use_power: false
  spectral_l2:
    p: 2
    calibration: 1
    use_power: false    
  wavelet:
    calibration: 1
    wavelet: 'sym4' 
    n_levels: 4 
    p: 1
  wavelet_complex:
    calibration: 1  
    n_levels: 4
    p: 1
    complex: true
  wavelet_l2:
    calibration: 1 
    wavelet: 'sym4' 
    n_levels: 4 
    p: 2
  wavelet_haar:
    calibration: 1  
    wavelet: 'haar' 
    n_levels: 4 
    p: 1
  wavelet_db4:
    calibration: 1
    wavelet: 'db4'
    n_levels: 4
    p: 1
  wavelet_sym4:
    calibration: 1
    wavelet: 'sym4'
    n_levels: 4
    p: 1
  wavelet_coif2:
    calibration: 1
    wavelet: 'coif2'
    n_levels: 4
    p: 1
  wavelet_bior1_3:
    calibration: 1
    wavelet: 'bior1.3'
    n_levels: 4
    p: 1
  wavelet_bior4_4:
    calibration: 1
    wavelet: 'bior4.4'
    n_levels: 4
    p: 1
  wavelet_rbio1_3:
    calibration: 1
    wavelet: 'rbio1.3'
    n_levels: 4
    p: 1
  wavelet_filtered:
    calibration: 1  
    limited_levels: [2, 3]
    complex: true
    n_levels: 4
    p: 1
  combo_mse_dssim:
    losses: ["mse", "dssim"]
    lambdas: [0.5, 0.5]
  combo_mse_spectral:
    losses: ["mse", "spectral"]
    lambdas: [0.5, 0.5]
  combo_mse_spectral_l2:
    losses: ["mse", "spectral_l2"]
    lambdas: [0.5, 0.5]
  combo_mse_wavelet:
    losses: ["mse", "wavelet_complex"]
    lambdas: [0.5, 0.5]
  combo_mse_gdl:
    losses: ["mse", "gdl"]
    lambdas: [0.5, 0.5]
  combo_mse_gdl_l1:
    losses: ["mse", "gdl_l1"]
    lambdas: [0.5, 0.5]    
  combo_mse_wavelet_filtered:
    losses: ["mse", "wavelet_filtered"]
    lambdas: [0.5, 0.5]
  combo_mse_nllbg:
    losses: ["mse", "nllbg"]
    lambdas: [0.5, 0.5]
  combo_fmse_dssim:
    losses: ["f_mse", "dssim"]
    lambdas: [0.5, 0.5]
  combo_fmse_spectral:
    losses: ["f_mse", "spectral"]
    lambdas: [0.5, 0.5]
  combo_fmse_wavelet:
    losses: ["f_mse", "wavelet_complex"]
    lambdas: [0.5, 0.5]
  combo_fmse_gdl:
    losses: ["f_mse", "gdl"]
    lambdas: [0.5, 0.5]
  combo_fmse_wavelet_filtered:
    losses: ["f_mse", "wavelet_filtered"]
    lambdas: [0.5, 0.5]
  combo_mse_dssim_spectral:
    losses: ["mse", "dssim", "spectral"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_spectral_wavelet:
    losses: ["mse", "spectral", "wavelet_complex"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]  
  combo_mse_wavelet_gdl:
    losses: ["mse", "wavelet_complex", "gdl"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_gdl_spectral:
    losses: ["mse", "gdl", "spectral"]   
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_dssim_wavelet:
    losses: ["mse", "dssim", "wavelet_complex"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_dssim_gdl:
    losses: ["mse", "dssim", "gdl"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_nllbg_dssim:
    losses: ["nllbg", "dssim"]
    lambdas: [0.5, 0.5]
  combo_nllbg_asym:
    losses: ["nllbg", "asym"]
    lambdas: [0.5, 0.5]
  combo_asym_spectral:
    losses: ["asym", "spectral"]
    lambdas: [0.5, 0.5]
  combo_dssim_asym:
    losses: ["dssim", "asym"]
    lambdas: [0.5, 0.5]    
  combo_mse_nllbg_spectral:
    losses: ["mse", "nllbg", "spectral"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_nllbg_gdl:
    losses: ["mse", "nllbg", "gdl"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_mse_nllbg_wavelet:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_nllbg_spectral:
    losses: ["nllbg", "spectral"]
    lambdas: [0.5, 0.5]
  combo_nllbg_wavelet:
    losses: ["nllbg", "wavelet_complex"]
    lambdas: [0.5, 0.5]
  combo_nllbg_spectral_wavelet:
    losses: ["nllbg", "spectral", "wavelet_complex"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_nllbg_dssim_spectral:
    losses: ["nllbg", "dssim", "spectral"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_nllbg_gdl:
    losses: ["nllbg", "gdl"]
    lambdas: [0.5, 0.5]
  combo_nllbg_spectral_gdl:
    losses: ["nllbg", "spectral", "gdl"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_nllbg_fmse_spectral:
    losses: ["nllbg", "f_mse", "spectral"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  combo_fmse_spectral_wavelet:
    losses: ["f_mse", "spectral", "wavelet_complex"]
    lambdas: [0.3333333, 0.3333333, 0.3333333]
  # testing different weightings
  # combo_nllbg_wavelet
  combo_nllbg_wavelet_19:
    losses: ["nllbg", "wavelet_complex"]
    lambdas: [0.1, 0.9]
  combo_nllbg_wavelet_37:
    losses: ["nllbg", "wavelet_complex"]
    lambdas: [0.3, 0.7]
  combo_nllbg_wavelet_73:
    losses: ["nllbg", "wavelet_complex"]
    lambdas: [0.7, 0.3]
  combo_nllbg_wavelet_91:
    losses: ["nllbg", "wavelet_complex"]
    lambdas: [0.9, 0.1]
  # combo_fmse_spectral
  combo_fmse_spectral_19:
    losses: ["f_mse", "spectral"]
    lambdas: [0.1, 0.9]
  combo_fmse_spectral_37:
    losses: ["f_mse", "spectral"]
    lambdas: [0.3, 0.7]
  combo_fmse_spectral_73:
    losses: ["f_mse", "spectral"]
    lambdas: [0.7, 0.3]
  combo_fmse_spectral_91:
    losses: ["f_mse", "spectral"]
    lambdas: [0.9, 0.1]
  # combo_mse_nllbg_wavelet
  combo_mse_nllbg_wavelet_136:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.1, 0.3, 0.6]
  combo_mse_nllbg_wavelet_163:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.1, 0.6, 0.3]
  combo_mse_nllbg_wavelet_316:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.3, 0.1, 0.6]
  combo_mse_nllbg_wavelet_361:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.3, 0.6, 0.1]
  combo_mse_nllbg_wavelet_613:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.6, 0.1, 0.3]
  combo_mse_nllbg_wavelet_631:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.6, 0.3, 0.1]
  combo_mse_nllbg_wavelet_811:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.8, 0.1, 0.1]
  combo_mse_nllbg_wavelet_181:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.1, 0.8, 0.1]
  combo_mse_nllbg_wavelet_118:
    losses: ["mse", "nllbg", "wavelet_complex"]
    lambdas: [0.1, 0.1, 0.8]    
  
  # You can defined more combinations
  # combo_name:
  #   losses: ["loss1", "loss2", ...]
  #   lambdas: [lambda1, lambda2, ...]
  # Make sure the sum of lambdas is 1.

# For display purposes
display:
  mse: "MSE"
  mae: "MAE"
  nllbg: "NLL-BG"
  asym: "Asym-MAE"
  gdl: "GDL"
  gdl_l1: "GDL (L1)"
  dssim: "DSSIM"
  f_mse: "F-MSE"
  f_mae: "F-MAE"
  wavelet: "Wavelet"
  wavelet_l2: "Wavelet (L2)"   
  spectral: "Spectral"
  spectral_l2: "Spec (L2)"
  wavelet_filtered: "Filtered wavelet"
  wasserstein: "Wasserstein"
  wavelet_haar: "Wavelet Haar"
  wavelet_db4: "Wavelet Daubechies 4"
  wavelet_sym4: "Wavelet Symlet 4"
  wavelet_coif2: "Wavelet Coiflet 2"
  wavelet_bior1_3: "Wavelet Biorthogonal 1.3"
  wavelet_bior4_4: "Wavelet Biorthogonal 4.4"
  wavelet_rbio1_3: "Wavelet Rev Biorthogonal 1.3"
  wavelet_complex: "Complex Wavelet"
short:
  mse: "MSE"
  mae: "MAE"
  gdl: "GDL"
  dssim: "DSSIM"
  nllbg: "NLL-BG"
  asym: "Asym-MAE"
  f_mse: "F-MSE"
  f_mae: "F-MAE"
  wavelet: "Wav"
  spectral: "Spec"
  wavelet_filtered: "Filt Wav"
  wavelet_complex: "C-Wav"